repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black
        language: system
        types: [python]
      - id: isort
        name: isort
        entry: poetry run isort
        language: system
        types: [python]
      - id: flake8
        name: flake8
        entry: poetry run flake8
        always_run: false
        language: system
        types: [python]
      - id: mypy
        name: mypy
        entry: poetry run mypy
        always_run: false
        language: system
        types: [python]
