repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black backend
        language: system
        types: [python]
      - id: isort
        name: isort
        entry: poetry run isort backend
        language: system
        types: [python]
      - id: flake8
        name: flake8
        entry: poetry run flake8 backend
        always_run: false
        language: system
        types: [python]
      - id: mypy
        name: mypy
        entry: poetry run mypy backend
        always_run: false
        language: system
        types: [python]
